@startuml

class User
class UserService
interface UserRepository
interface PasswordEncoder

UserService --> UserRepository
UserService --> PasswordEncoder
UserRepository ..> User
UserService ..> User

@enduml